# Generated by Django 5.1.3 on 2024-11-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
